repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
    -   id: mypy
        args: ['--strict']
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.297
    hooks:
    - id: pyright
-   repo: local
    hooks:
      - id: unittest
        name: python tests py3.7
        entry: env SEAMFUL_DISABLE_ERROR_DEFINITION_LINE=1 python -m unittest discover src
        language: python
        language_version: python3.7
        pass_filenames: false
        stages: [ commit ]
      - id: unittest
        name: python tests py3.8
        entry: env SEAMFUL_DISABLE_ERROR_DEFINITION_LINE=1 python -m unittest discover src
        language: python
        language_version: python3.8
        pass_filenames: false
        stages: [ commit ]
      - id: unittest
        name: python tests py3.9
        entry: env SEAMFUL_DISABLE_ERROR_DEFINITION_LINE=1 python -m unittest discover src
        language: python
        language_version: python3.9
        pass_filenames: false
        stages: [ commit ]
      - id: unittest
        name: python tests py3.10
        entry: env SEAMFUL_DISABLE_ERROR_DEFINITION_LINE=1 python -m unittest discover src
        language: python
        language_version: python3.10
        pass_filenames: false
        stages: [ commit ]
      - id: unittest
        name: python tests py3.11
        entry: env SEAMFUL_DISABLE_ERROR_DEFINITION_LINE=1 python -m unittest discover src
        language: python
        language_version: python3.11
        pass_filenames: false
        stages: [ commit ]
